spring:
  application:
    name: Park
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: secret
  flyway:
    baseline-on-migrate: true
    schemas: public
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true